name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - run: go mod download
      - run: go vet ./...
      - run: |
          go install honnef.co/go/tools/cmd/staticcheck@v0.1.3
          staticcheck -tests ./...
